def application
def gitRepo

pipeline {

  agent any 
environment {
DOCKERHUBCRED = credentials('DOCKERHUB')
}
  stages{

stage("Read Properties file") {
steps{
script {
props = readProperties file: "devops/ci/pipeline.properties"
  application = evaluate(props['application']).toString()
  gitRepo = evaluate(props['gitRepo']).toString()

}
}
}
    stage("Source Code Fetch") {
steps {
script {
  checkout scmGit(branches: [[name: '**']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/Ravi-s10/docker-app']])
//checkout([$class: 'gitSCM' ,branches: [["${GIT_BRANCH}"]] ,gitTool: 'Default' ,userRemoteConfigs: [[url = "${gitRepo}"]]])

}
  

}

    }
/*
   stage("Build Docker image"){
  steps{
                     
 sh "docker build -t ${application}_${BUILD_NUMBER} ."
                     
 }
}

    stage("Login to Dockerhub") {
steps{
  sh "echo $DOCKERHUBCRED | docker login -u ravis10 --password-stdin"
  echo "Login Success"
}

    }
    */

    stage("Buidl and Push") {
steps{
script{
withDockerRegistry(credentialsId: 'dockehub'){
  sh "docker build -t ravis10/nginx:${BUILD_NUMBER} ."
  sh "docker push ravis10/nginx:${BUILD_NUMBER}"
}
}
}
    }



  }
  
}
