def application
def gitRepo

pipeline {

  agent any 

  stages{

stage("Read Properties file") {
steps{
script {
props = readProperties file "devops/ci/pipeline.properties"
  application = evaluate(props['application]).toString()
  gitRepo = evaluate(props['gitRepo']).toString()

}
}
}
    stage("Source Code Fetch") {
steps {
script {
checkout([$class: 'gitSCM' ,branches: [["${GIT_BRANCH}"]] ,gitTool: 'Default' ,userRemoteConfigs: [[url = "${gitRepo}"]]])

}
  

}

    }

                               stage("Build Docker image"){
                          steps{
                      script{
                        docker ps
                      }
                          }
                               }
    



  }
  
}
