pipeline {
  agent any 
  parameters{
    string(
      name: 'HOST_PORT',
      defaultValue: '83',
      description: 'Enter host port to run conatiner'
    )
    string(
      name: 'CONTAINER_PORT',
      defaultValue: '80',
      description: 'Enter container port no'
    )
    string(
      name: 'IMAGE',
      defaultValue: 'ravis10/nginx:5'
      description: 'Enter image name'
      
    )
    string(
      name: 'NAME',
      defaultValue: 'nginx-demo'
      description: 'Enter conatiner name'
      
    )
  }
stages{
  stage("Run Conatiner") {
    steps{
      sh "docker run -dt --name ${NAME} -p ${HOST_PORT}:${CONTAINER_PORT} ${IMAGE}"
    }
  }
}
}
