pipeline {
  agent any 
  parameters{
    string(
      name: 'HOST_PORT',
      defaultValue: 83,
      description: 'Enter host port to run conatiner'
    )
    string(
      name: 'CONTAINER_PORT',
      defaultValue: 80,
      description: 'Enter container port no'
    )
  }
stages{
  stage("Run Conatiner") {
    steps{
      sh "doker run -dt -p ${HOST_PORT}:${CONTAINER_PORT}
    }
  }
}
}
